 FROM ubuntu:latest
 FROM python:3.8.1
 COPY . /app
 WORKDIR app
  RUN pip3 install -r requirements.txt
 #RUN pip3 install --no-cache-dir -r requirements.txt
CMD ["python3", "./HomeQuiz.py"]
#CMD ["export", " FLASK_ENV=HomeQuiz.py; flask run"]